config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :jobs, only: [:show, :new, :create, :edit, :update]
  resources :companies, only: [:show, :new, :create, :edit, :update]
  resources :categories, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
  validates :name, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
  validates :name, :location, :mail, :phone, presence: true

  def premium?
    jobs.count >= 5 ? true : false
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :category
  validates :title, :location, :category_id, :description, :company_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @jobs = @category.jobs
    if @jobs.empty?
      flash.now[:notice] = 'Nenhuma vaga disponível'
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      redirect_to @category
    else
      flash.now[:notice] = 'Nao foi possivel criar categoria'
      render :new
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def show
    @company = Company.find(params[:id])
    @jobs = @company.jobs
    if @jobs.empty?
      flash.now[:notice] = 'Nenhuma vaga disponível'
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params.require(:company).permit(:name, :location, :mail, :phone))
    if @company.save
      redirect_to @company
    else
      flash.now[:notice] = 'Não foi possível criar empresa'
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(params.require(:company).permit(:name, :location, :mail, :phone))
      redirect_to @company
    else
      flash.now[:notice] = 'Não foi possivel atualizar a empresa'
      render :edit
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @jobs = Job.all
    @companies = Company.all
    @categories = Category.all
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update]
  before_action :set_collections, only: [:new, :edit]

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to @job
    else
      flash.now[:notice] = 'Não foi possível criar a vaga'
      set_collections
      render :new
    end
  end

  def edit
  end

  def update
     if @job.update(job_params)
      redirect_to @job
    else
      flash.now[:notice] = 'Não foi possível atualizar a vaga'
      set_collections
      render :edit
    end
  end

  private
  def job_params
    params.require(:job).permit(:title, :company_id, :description, :location, :category_id, :featured)
  end

  def set_collections
    @companies = Company.all
    @categories = Category.all
  end

  def find_job
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_categories_list.html.erb
<div>
    <h1 class="text-center">Categorias</h1>
    <div class="list-group">
        <% categories.each do |category| %>
        <div class="list-group-item text-center"><%= link_to category.name, category%></div>
        <% end %>
    </div>
</div>

app/views/categories/new.html.erb
<section>
    <h1>Nova Categoria</h1>
    <%= simple_form_for @category do |f| %>
      <%= f.input :name, label: 'Nome' %>
      <%= f.submit 'Criar Categoria', class: "btn btn-primary" %>
    <% end %>
</section>

app/views/categories/show.html.erb
<section>
    <h1><%= @category.name %></h1>
    <div>
        <%= render @jobs%>
    </div>
</section>

app/views/companies/_companies_list.html.erb
<div>
    <h1 class="text-center">Empresas</h1>
    <div class="list-group">
        <% companies.each do |company| %>
          <div class="list-group-item text-center"><%= link_to company.name, company%></div>
        <% end %>
    </div>
</div>

app/views/companies/edit.html.erb
<section>
  <h1>Editar Empresa</h1>
  <%= simple_form_for @company do |f| %>
    <%= f.input :name, label: 'Nome' %>
    <%= f.input :location, label: 'Local' %>
    <%= f.input :mail, label: 'Email' %>
    <%= f.input :phone, label: 'Telefone' %>
    <%= f.button :submit, 'Atualizar Empresa' %>
  <% end %>
</section>

app/views/companies/new.html.erb
<section>
  <h1>Nova Empresa</h1>
  <%= simple_form_for @company do |f| %>
    <%= f.input :name, label: 'Nome'%>
    <%= f.input :location, label: 'Local'%>
    <%= f.input :mail, label: 'Email'%>
    <%= f.input :phone, label: 'Telefone'%>
    <%= f.button :submit, 'Criar Empresa', class: "btn btn-primary" %>
  <% end %>
</section>

app/views/companies/show.html.erb
<section>
    <div>
        <div class="row">
            <div class="col-md-12">
                <h1><%= @company.name %>
                    <% if @company.premium? %>
                    <%= image_tag 'estrela', alt: 'empresa premium', id: 'EmpresaPremium' %>
                    <% end %>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <dl>
                    <dt>Local</dt>
                    <dd><%= @company.location %></dd>
                    <dt>Email</dt>
                    <dd><%= @company.mail %></dd>
                    <dt>Telefone</dt>
                    <dd><%= @company.phone %></dd>
                </dl>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <%= render @jobs %>
        </div>
    </div>
</section>

app/views/home/index.html.erb
<div class="row">
    <div class="col-md-9">
        <section class="jobs">
            <div class="row">
                <% @jobs.each do |job| %>
                <div class="col-md-6">
                    <%= render job %>
                </div>
                <% end %>
            </div>
        </section>
    </div>

    <div class="col-md-3">
        <aside class="companies">
            <%= render partial: 'companies/companies_list', locals: {companies: @companies} %>
        </aside>
        <aside class="categories">
            <%= render partial: 'categories/categories_list', locals: {categories: @categories} %>
        </aside>
    </div>
</div>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :title, label: 'Título'%>
  <%= f.input :company_id, label: 'Empresa', collection: @companies %>
  <%= f.input :location, label: 'Local'%>
  <%= f.input :category_id, label: 'Categoria', collection: @categories %>
  <%= f.input :description, label: 'Descrição'%>
  <%= f.input :featured, label: 'Destaque', as: :boolean %>
  <%= f.button :submit, submit_text, class: "btn btn-primary" %>
<% end %>

app/views/jobs/_job.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="small"><%= link_to job.title, job %>
            <% if job.featured? %>
            <strong>Destaque</strong>
            <% end %>
        </h1>

    </div>
    <div class="panel-body">
        <dl>
            <dt>Empresa</dt>
            <dd><%= job.company.name%></dd>
            <dt>Categoria</dt>
            <dd><%= job.category.name%></dd>
            <dt>Local</dt>
            <dd><%= job.location%></dd>
        </dl>
    </div>
</div>

app/views/jobs/edit.html.erb
<section>
    <div>
        <h1>Editar Empresa</h1>
        <%= render partial: 'form', locals: {submit_text: 'Atualizar Vaga'} %>
    </div>
</section>

app/views/jobs/new.html.erb
<section>
    <div class="">
      <h1>Nova vaga</h1>
        <%= render partial: 'form', locals: {submit_text: 'Criar Vaga'}%>
    </div>
</section>

app/views/jobs/show.html.erb
<section>
    <div>
        <h1><%= @job.title %></h1>
        <div class="destaque">
            <strong>Destaque</strong>
        </div>
        <hr>
        <dl class="dl-horizontal">
            <dt>Categoria</dt>
            <dd><%= @job.category.name %></dd>
            <dt>Descrição</dt>
            <dd><%= @job.description %></dd>
            <dt>Empresa</dt>
            <dd><%= @job.company.name %></dd>
            <dt>Local</dt>
            <dd><%= @job.location %></dd>
        </dl>
    </div>
</section>

<%= link_to 'Editar Vaga', edit_job_path, class: "btn btn-primary" %>
<%= link_to 'Voltar', root_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>EmpregoJa</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <h1><%= link_to 'Emprego Já', root_path, class: "navbar-brand" %></h1>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><%= link_to 'Nova Vaga', new_job_path%></li>
                        <li><%= link_to 'Nova Empresa', new_company_path%></li>
                        <li><%= link_to 'Nova Categoria', new_category_path%></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <%= yield %>
            <div class="bg-danger">
                <%= notice %>
            </div>
        </div>

    </body>
</html>